const VALUE_LABELS: Record<string, string> = {
  "3PL_INTERNAL_LABEL": "Depo etiketi",
  "0d": "Bugün",
  "1d": "1 gün",
  "CHINA_HK_DIRECT_DDP": "Çin/HK direkt DDP",
  DIRECT_DDP_PROVIDER: "DDP sağlayıcısı",
  EU_3PL: "Avrupa deposu",
  "FACTORY-CN-01": "Çin üretim",
  MANUAL_SPECIAL: "Özel manuel yol",
  PARTNER_MANAGED: "Partner yönetir",
  REGIONAL_3PL: "Bölgesel depo",
  SFC_ASIA_DIRECT_DDP: "SFC Asya direkt DDP",
  "SFC-CN-01": "SFC Çin hub",
  SFC_CHINA: "SFC Çin ana depo",
  SFC_DIRECT: "SFC direkt gönderim",
  SFC_TO_EU_FREIGHT_EASYSHIP: "SFC Avrupa freight + Easyship",
  SFC_TO_US_FREIGHT_EASYSHIP: "SFC Amerika freight + Easyship",
  "US-3PL-01": "Amerika 3PL",
  US_3PL: "Amerika deposu",
  accepted: "Kabul edildi",
  all: "Tümü",
  "awaiting signed event": "İmzalı ödeme haberi bekleniyor",
  blocked: "Blokaj",
  blocker: "Blokaj",
  "blocked_non_critical": "Şimdilik sorun değil",
  "covered approval": "Owner onaylı ödeme",
  complete: "Tamam",
  "currency_review_required": "Para birimi kontrolü",
  "dev ready": "Geliştirmeye hazır",
  disabled: "Kapalı",
  draft: "Taslak",
  "easyship_mock_only": "Easyship maket modda",
  "easyship_production_blocked": "Easyship canlı kapalı",
  "easyship_sandbox_ready": "Easyship sandbox hazır",
  "easyship_token_invalid_shape": "Easyship token geçersiz",
  "easyship_token_missing": "Easyship token eksik",
  exported: "Dışa aktarıldı",
  failed: "Hata",
  "feed_ready": "Feed hazır",
  fresh: "Güncel fiyat",
  incoming: "Yolda",
  "local_staging_without_vercel_git": "Yerel + staging modu",
  "lock_ready": "Kilit hazır",
  "manual DDP review": "Manuel DDP kontrolü",
  "manual needed": "Elle fiyat gerekli",
  "manual_hold": "Manuel beklet",
  "mock_created": "Maket kayıt oluşturuldu",
  "missing_product_master_sku": "Ürün kodu sistemde yok",
  missing: "Eksik",
  "missing dimensions": "Ölçü eksik",
  "missing HS/origin/value": "Gümrük bilgisi eksik",
  "needs_review": "Kontrol gerekli",
  "not connected": "Bağlı değil",
  "not dev blocker": "Geliştirmeyi durdurmaz",
  "not needed": "Gerekmez",
  none: "Yok",
  "no_demand": "Talep yok",
  pending: "Bekliyor",
  partial: "Kısmi stok",
  "payment_amount_mismatch": "Ödeme tutarı uyuşmuyor",
  "payment_pending": "Ödeme bekliyor",
  "label_pending": "Etiket bekliyor",
  "rates_ready": "Fiyat hazır",
  "payment_review_required": "Ödeme kontrolü gerekli",
  "owner action needed": "Owner aksiyonu gerekli",
  "manual-ddp-preview": "Manuel DDP önizleme",
  "quote ready": "Fiyat hazır",
  ready: "Hazır",
  review: "Kontrol et",
  required: "Gerekli",
  "safe preview": "Güvenli önizleme",
  "selection_submitted": "Seçim kaydedildi",
  short: "Stok açık",
  "sfc_credentials_missing": "SFC anahtarları eksik",
  "sfc_mock_only": "SFC maket modda",
  "sfc_mutation_blocked": "SFC canlı işlem kapalı",
  "sfc_read_only_env_not_ready": "SFC read-only env eksik",
  "sfc_read_only_plan_blocked": "SFC smoke plan bloklu",
  "sfc_read_only_plan_ready": "SFC smoke plan hazır",
  "sfc_read_only_ready": "SFC read-only hazır",
  "staging_ready": "Staging hazır",
  "stock_ready": "Stok hazır",
  "local_preview": "Yerel önizleme",
  "blocking": "Blokaj",
  "warning": "Uyarı",
  "test ready": "Test hazır",
  later: "Sonraki pilot",
  "approval needed": "Onay gerekli",
  "api-base-url": "API adresi",
  "api-token": "API anahtarı",
  "checkout-flag": "Ödeme ekranı kapısı",
  "environment-mode": "Ortam modu",
  "fulfillment-supabase": "Fulfillment Supabase",
  "live-export-disabled": "Canlı dışa aktarım kapalı",
  "live-mutation-flags": "Canlı değiştirme kapalı",
  "partner-api-push": "Partner API gönderimi",
  "partner-api-push-disabled": "Partner API gönderimi kapalı",
  "pm-supabase-blocklist": "PM veritabanı koruması",
  "pm-supabase-guard": "PM veritabanı koruması",
  "provider-api-quotes": "Kargo firması fiyat API",
  "provider-api-quotes-disabled": "Kargo firması fiyat API kapalı",
  "publishable-test-key": "Yayınlanabilir test anahtarı",
  "restricted-test-key": "Kısıtlı test anahtarı",
  "stripe-checkout": "Stripe ödeme ekranı",
  "stripe-checkout-disabled": "Stripe ödeme ekranı kapalı",
  "stripe_checkout_disabled": "Stripe ödeme ekranı kapalı",
  "stripe_checkout_ready": "Stripe test ödemesi hazır",
  "stripe_live_mode_blocked": "Stripe canlı mod kapalı",
  "stripe_publishable_key_invalid": "Stripe test anahtarı hatalı",
  "stripe_restricted_test_key_missing": "Kısıtlı test anahtarı eksik",
  "stripe_restricted_test_key_required": "Kısıtlı test anahtarı gerekli",
  "stripe-mode": "Stripe modu",
  "supabase-target": "Supabase hedefi",
  "synthetic-fixtures": "Test verileri",
  "handoff-exports-disabled": "Canlı kargo dosyası kapalı",
  "launch-readiness": "Canlı yayın hazırlığı",
  "live-actions": "Sandbox işlem kapıları",
  "vercel-git-integration": "Vercel Git bağlantısı",
};

const COLUMN_LABELS: Record<string, string> = {
  action: "Sıradaki iş",
  address: "Adres",
  age: "Bekleme",
  amountDelta: "Tutar farkı",
  code: "Sorun",
  country: "Ülke",
  currentAmount: "Güncel tutar",
  customs: "Gümrük",
  exportType: "Dosya türü",
  destination: "Varış",
  expires: "Geçerlilik",
  guard: "Güvenlik kontrolü",
  item: "İş",
  metric: "Özet",
  mode: "Kargo modu",
  originalAmount: "Orijinal tutar",
  owner: "Sorumlu",
  packaging: "Paket bilgisi",
  package: "Paket",
  label: "Etiket",
  payment: "Ödeme",
  priority: "Sıra",
  products: "Ürünler",
  quote: "Fiyat",
  queue: "Kuyruk",
  route: "Kargo yolu",
  severity: "Önem",
  sku: "SKU",
  sourceOrderKey: "Sipariş",
  status: "Durum",
  title: "Ürün",
  value: "Adet",
  available: "Ayrılabilir",
  demand: "Talep",
  onHand: "Eldeki",
  produced: "Üretilen",
  shortage: "Açık",
};

export function formatColumnLabel(column: string) {
  return COLUMN_LABELS[column] ?? column.replace(/([a-z])([A-Z])/g, "$1 $2").replace(/_/g, " ");
}

export function formatOpsValue(_column: string, value: string) {
  return VALUE_LABELS[value] ?? value;
}

export function opsStatusTone(label: string) {
  const normalized = label.toLowerCase();

  if (["ready", "quote ready", "completed", "dev ready", "test ready", "safe preview", "lock_ready", "feed_ready", "stock_ready"].includes(normalized)) {
    return "good";
  }
  if (["hazır", "güvenli", "tamam", "test hazır", "geliştirmeye hazır"].some((value) => normalized.includes(value))) return "good";
  if (["blocker", "blocked", "missing hs/origin/value", "payment_review_required", "short"].some((value) => normalized.includes(value))) return "danger";
  if (["blokaj", "hata", "uyuşmuyor", "canlı kapalı"].some((value) => normalized.includes(value))) return "danger";
  if (["review", "pending", "approval", "missing", "draft", "disabled", "not connected", "incoming", "partial"].some((value) => normalized.includes(value))) {
    return "warning";
  }
  if (["kontrol", "bekliyor", "eksik", "taslak", "kapalı", "bağlı değil", "onay"].some((value) => normalized.includes(value))) return "warning";

  return "neutral";
}
